### ISSUE TITLE
packaging slide - the supplied 'ls' command is not very instructive

### ISSUE THREAD

**Issue by jmMeessen** [oufti-playground/devfest-lille-2017#6]
What is the intention of command `ls -lrh ./target/` ? 

I would suppose, show the files that were added since the last maven command.

I believe that `ls -lch` works better.

**Comment by dduportal** [comment]
I think that I wanted to use the `t` option: `ls -ltrh` , which list the content of the directory with: 

* Details metadatas per inode (flag `l`)
* Humanly readable size (flag `h`) 
* Sort by time (flag `t`)
* Invert sorting (flag `r`)

=> You have the most recent files in the bottom.

I need to correct this thanks !

**Comment by jmMeessen** [comment]
Fixed
